const NameKeys0 = {
  Escape: "ESC",
  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",
  Digit0: "0",
  Minus: "-",
  Plus: "+", //*
  Backspace: "BACK",
};
const NameKeys1 = {
  Tab: "TAB",
  KeyQ: "Q",
  KeyW: "W",
  KeyE: "E",
  KeyR: "R",
  KeyT: "T",
  KeyY: "Y",
  KeyU: "U",
  KeyI: "I",
  KeyO: "O",
  KeyP: "P",
  BracketLeft: "[",
  BracketRight: "]",
  BackSlash: "\\",
};
const NameKeys2 = {
  CapsLock: "CAPS",
  KeyA: "A",
  KeyS: "S",
  KeyD: "D",
  KeyF: "F",
  KeyG: "G",
  KeyH: "H",
  KeyJ: "J",
  KeyK: "K",
  KeyL: "L",
  Colon: ":",
  DoubleQuote: '"',
  Enter: "ENTER",
};
const NameKeys3 = {
  ShiftLeft: "SHIFT",
  KeyZ: "Z",
  KeyX: "X",
  KeyC: "C",
  KeyV: "V",
  KeyB: "B",
  KeyN: "N",
  KeyM: "M",
  Comma: ",",
  Period: ".",
  Slash: "/",
  ShiftRight: "SHIFT",
};
const NameKeys4 = {
  ControlLeft: "CTRL",
  OSLeft: "Win",
  AltLeft: "ALT",
  Space: "",
  AltRight: "ALT",
  ControlRight: "CTRL",
  Arrow: "",
};

const NameKeysClass = {
  Escape: "lilF",
  Digit1: "lilF",
  Digit2: "rF",
  Digit3: "mF",
  Digit4: "iF",
  Digit5: "iF",
  Digit6: "iF",
  Digit7: "iF",
  Digit8: "mF",
  Digit9: "rF",
  Digit0: "lilF",
  Minus: "lilF",
  Plus: "lilF", //*
  Backspace: "lilF",
  Tab: "lilF",
  KeyQ: "lilF",
  KeyW: "rF",
  KeyE: "mF",
  KeyR: "iF",
  KeyT: "iF",
  KeyY: "iF",
  KeyU: "iF",
  KeyI: "mF",
  KeyO: "rF",
  KeyP: "lilF",
  BracketLeft: "lilF",
  BracketRight: "lilF",
  BackSlash: "lilF",
  CapsLock: "lilF",
  KeyA: "lilF",
  KeyS: "rF",
  KeyD: "mF",
  KeyF: "iF",
  KeyG: "iF",
  KeyH: "iF",
  KeyJ: "iF",
  KeyK: "mF",
  KeyL: "rF",
  Colon: "lilF",
  DoubleQuote: "lilF",
  Enter: "lilF",
  ShiftLeft: "lilF",
  KeyZ: "lilF",
  KeyX: "rF",
  KeyC: "mF",
  KeyV: "iF",
  KeyB: "iF",
  KeyN: "iF",
  KeyM: "iF",
  Comma: "mF",
  Period: "rF",
  Slash: "lilF",
  ShiftRight: "lilF",
  ControlLeft: "lilF",
  OSLeft: "lilF",
  AltLeft: "thumbF",
  Space: "thumbF",
  AltRight: "thumbF",
  ControlRight: "lilF",
  Arrow: "lilF",
};
const InputDisplayTexts = [
  "It is a curious thing, Harry, but perhaps those who are best suited to power are those who have never sought it. Those who, like you, have leadership thrust upon them, and take up the mantle because they must, and find to their own surprise that they wear it well",
  "Spoken like a true leader. But since your failure as a leader is a virtual certainty, tolerating your short reign as CEO in exchange for a front-row seat to the disaster seems fair. Plus, if I'm wrong, which I'm not, I get rich. So I'm down with it, Dinesh.",
  "Tyrion Lannister recognizes Jon Snow as the illegitimate son of Ned Stark and calls him a bastard. This does offend Jon Snow to a great degree. This is when Lannister gives him some advice… Never forget what you are. The rest of the world will not. Wear it like armour, and it can never be used to hurt you.",
  "The hole in one's heart gets filled by others around you. Friends won't flock to someone who abandons the memory of his friends and gives up on the world just because things don't go the way he wants them to. And people won't help those who run away and do nothing. As long as you don't give up, there will always be salvation.",
  "Iron Man achieved something rare for a superhero. They made a hero who was just as interesting outside of the costume as he was inside the costume. Instead of playing the secret identity game, Tony Stark and Iron Man are one and the same and this becomes the mantra for the character.",
  "There is a kind of fallout that happens when you leave college. Your professor gets paid to pay attention to your ideas, and your classmates are paying to pay attention to your ideas. Never again in your life will you have such a captive audience. It’s not that people are mean or cruel, they’re just busy.",
];
export {
  NameKeys0,
  NameKeys1,
  NameKeys2,
  NameKeys3,
  NameKeys4,
  NameKeysClass,
  InputDisplayTexts,
};
