const NameKeys0 = {
  Escape: "ESC",
  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",
  Digit0: "0",
  Minus: "-",
  Plus: "+", //*
  Backspace: "BACK",
};
const NameKeys1 = {
  Tab: "TAB",
  KeyQ: "Q",
  KeyW: "W",
  KeyE: "E",
  KeyR: "R",
  KeyT: "T",
  KeyY: "Y",
  KeyU: "U",
  KeyI: "I",
  KeyO: "O",
  KeyP: "P",
  BracketLeft: "[",
  BracketRight: "]",
  BackSlash: "\\",
};
const NameKeys2 = {
  CapsLock: "CAPS",
  KeyA: "A",
  KeyS: "S",
  KeyD: "D",
  KeyF: "F",
  KeyG: "G",
  KeyH: "H",
  KeyJ: "J",
  KeyK: "K",
  KeyL: "L",
  Colon: ":",
  DoubleQuote: '"',
  Enter: "ENTER",
};
const NameKeys3 = {
  ShiftLeft: "SHIFT",
  KeyZ: "Z",
  KeyX: "X",
  KeyC: "C",
  KeyV: "V",
  KeyB: "B",
  KeyN: "N",
  KeyM: "M",
  Comma: ",",
  Period: ".",
  Slash: "/",
  ShiftRight: "SHIFT",
};
const NameKeys4 = {
  ControlLeft: "CTRL",
  OSLeft: "Win",
  AltLeft: "ALT",
  Space: "",
  AltRight: "ALT",
  ControlRight: "CTRL",
  Arrow: "",
};

const NameKeysClass = {
  Escape: "lilF",
  Digit1: "lilF",
  Digit2: "rF",
  Digit3: "mF",
  Digit4: "iF",
  Digit5: "iF",
  Digit6: "iF",
  Digit7: "iF",
  Digit8: "mF",
  Digit9: "rF",
  Digit0: "lilF",
  Minus: "lilF",
  Plus: "lilF", //*
  Backspace: "lilF",
  Tab: "lilF",
  KeyQ: "lilF",
  KeyW: "rF",
  KeyE: "mF",
  KeyR: "iF",
  KeyT: "iF",
  KeyY: "iF",
  KeyU: "iF",
  KeyI: "mF",
  KeyO: "rF",
  KeyP: "lilF",
  BracketLeft: "lilF",
  BracketRight: "lilF",
  BackSlash: "lilF",
  CapsLock: "lilF",
  KeyA: "lilF",
  KeyS: "rF",
  KeyD: "mF",
  KeyF: "iF",
  KeyG: "iF",
  KeyH: "iF",
  KeyJ: "iF",
  KeyK: "mF",
  KeyL: "rF",
  Colon: "lilF",
  DoubleQuote: "lilF",
  Enter: "lilF",
  ShiftLeft: "lilF",
  KeyZ: "lilF",
  KeyX: "rF",
  KeyC: "mF",
  KeyV: "iF",
  KeyB: "iF",
  KeyN: "iF",
  KeyM: "iF",
  Comma: "mF",
  Period: "rF",
  Slash: "lilF",
  ShiftRight: "lilF",
  ControlLeft: "lilF",
  OSLeft: "lilF",
  AltLeft: "thumbF",
  Space: "thumbF",
  AltRight: "thumbF",
  ControlRight: "lilF",
  Arrow: "lilF",
};
export { NameKeys0, NameKeys1, NameKeys2, NameKeys3, NameKeys4, NameKeysClass };
